### PR TITLE
008 view band training

### PR DESCRIPTION
**Pull request by TheoHodges**
As a Kainos Employee
I want to view training available/recommended for each band
So that I know the training recommended for employees at each band level

Acceptance criteria
- Can view and follow link to training information for each band on SharePoint

### CODE REVIEW

**Review by michaltangri — CHANGES_REQUESTED** [review]
Please change the `BandTrainingService bandTrainingService;` field in **BandTrainingController.java** to be private.

I think the same problem is in **BandService.java** and **BandTrainingService**

Also, almost all of JobRoleService.java is commented out, could you take a look at that?

**Review by michaltangri — APPROVED** [review]
Did not find any problems

**Review by sebastianczajkowski — APPROVED** [review]
Looks good

**Comment by TheoHodges** [comment]
Moved to 008-conflicts-resolved

**Pull request closed without merging**
